# Generated by Django 5.2.17 on 2026-09-01 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_remove_guard_assigned_gate_id_guard_assigned_gate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('requested_by', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('purpose', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('required_date_time', models.DateTimeField()),
                ('expected_return', models.DateTimeField(blank=True, null=True)),
                ('approver', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=12)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-required_date_time'],
            },
        ),
    ]
