# Generated by Django 5.2.17 on 2026-09-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_superadmin'),
    ]

    operations = [
        # No default needed: this is the first time accounts_kioskdevice/accounts_user
        # are ever created in the public schema (the app just moved from TENANT_APPS to
        # SHARED_APPS — see settings/base.py) — the table is empty, so there are no
        # existing rows to backfill a value for.
        migrations.AddField(
            model_name='kioskdevice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_devices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
