# Generated by Django 5.2.17 on 2026-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kioskdevice_tenant_user_tenant_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='app',
            field=models.CharField(blank=True, choices=[('exit', 'Exit'), ('entry', 'Entry'), ('fuel', 'Fuel')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='device_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='installation_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
