# Generated by Django 5.2.17 on 2026-09-01 00:53

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_remove_guard_assigned_gate_id_guard_assigned_gate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField()),
                ('workshop', models.CharField(max_length=120)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('engine', 'Engine'), ('transmission', 'Transmission'), ('brakes', 'Brakes'), ('suspension', 'Suspension'), ('electrical', 'Electrical'), ('ac', 'Ac'), ('tyres', 'Tyres'), ('other', 'Other')], max_length=15), size=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('next_due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tyre_code', models.CharField(max_length=30, unique=True)),
                ('brand', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=40)),
                ('serial_number', models.CharField(max_length=60)),
                ('wheel_position', models.CharField(blank=True, default='', max_length=40)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('install_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_life_km', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_use', 'In Use'), ('spare', 'Spare'), ('scrap', 'Scrap'), ('store', 'Store')], default='store', max_length=10)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['tyre_code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'in_use')), fields=('vehicle', 'wheel_position'), name='unique_in_use_tyre_per_wheel_position')],
            },
        ),
    ]
