# Generated by Django 5.2.17 on 2026-08-31 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('company_id_code', models.CharField(blank=True, default='', max_length=40)),
                ('cnic', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('licence_number', models.CharField(max_length=40)),
                ('licence_category', models.CharField(max_length=20)),
                ('licence_expiry', models.DateField()),
                ('department', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=40)),
                ('father_husband_name', models.CharField(blank=True, default='', max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10)),
                ('residential_address', models.TextField(blank=True, default='')),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('total_experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('access_level', models.CharField(blank=True, default='', max_length=40)),
                ('uniform_issued', models.BooleanField(default=False)),
                ('id_card_issued', models.BooleanField(default=False)),
                ('rfid_access_card', models.BooleanField(default=False)),
                ('night_duty_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guard_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('cnic', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('assigned_gate_id', models.CharField(blank=True, default='', max_length=20)),
                ('duty_shift', models.CharField(blank=True, default='', max_length=80)),
                ('guard_type', models.CharField(max_length=60)),
                ('authorized_exit', models.BooleanField(default=True)),
                ('authorized_in', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guards/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('registration_number', models.CharField(max_length=32, unique=True)),
                ('company', models.CharField(max_length=120)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('variant', models.CharField(blank=True, default='', max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('colour', models.CharField(max_length=40)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('other', 'Other')], max_length=10)),
                ('engine_number', models.CharField(blank=True, default='', max_length=80)),
                ('chassis_number', models.CharField(blank=True, default='', max_length=80)),
                ('department_cost_centre', models.CharField(blank=True, default='', max_length=120)),
                ('expected_fuel_average_kmpl', models.FloatField()),
                ('current_odometer', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('outside', 'Outside'), ('workshop', 'Workshop'), ('inactive', 'Inactive')], default='available', max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('qr_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('seating_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='', max_length=10)),
                ('drive_type', models.CharField(blank=True, default='', max_length=20)),
                ('body_type', models.CharField(blank=True, default='', max_length=40)),
                ('fuel_average_alert_low', models.FloatField(blank=True, null=True)),
                ('fuel_average_alert_high', models.FloatField(blank=True, null=True)),
                ('oil_change_km', models.PositiveIntegerField(blank=True, null=True)),
                ('tyre_change_km', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_filter_change_km', models.PositiveIntegerField(blank=True, null=True)),
                ('gear_oil_change_km', models.PositiveIntegerField(blank=True, null=True)),
                ('timing_belt_change_km', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_to_exit', models.BooleanField(default=True)),
                ('allowed_to_exit_reason', models.CharField(blank=True, default='', max_length=255)),
                ('allowed_to_exit_updated_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_to_exit_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle_of', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('purpose', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('requested_by', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('approved_by', models.CharField(blank=True, default='', max_length=120)),
                ('out_time', models.DateTimeField()),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('odometer_out', models.PositiveIntegerField()),
                ('odometer_in', models.PositiveIntegerField(blank=True, null=True)),
                ('trip_km', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=10)),
                ('return_condition', models.CharField(blank=True, choices=[('ok', 'Ok'), ('maintenance_required', 'Maintenance Required'), ('damage_incident', 'Damage Incident')], default='', max_length=25)),
                ('remarks', models.TextField(blank=True, default='')),
                ('expected_return', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.driver')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.guard')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle'),
        ),
    ]
