# Generated by Django 5.2.17 on 2026-09-01 00:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='assigned_gate_id',
        ),
        migrations.AddField(
            model_name='guard',
            name='assigned_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guards', to='masterdata.gatemaster'),
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('odometer', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('other', 'Other')], max_length=10)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fuel_station', models.CharField(max_length=120)),
                ('payment_method', models.CharField(max_length=40)),
                ('receipt_no', models.CharField(blank=True, default='', max_length=60)),
                ('full_tank', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_entries', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_entries', to='fleet.vehicle')),
            ],
            options={
                'verbose_name_plural': 'fuel entries',
                'ordering': ['-date_time'],
            },
        ),
    ]
