# Generated by Django 5.2.17 on 2026-09-06 21:21

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_guard_company_id_code_alter_driver_company_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.driver_photo_path),
        ),
        migrations.AlterField(
            model_name='guard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.guard_photo_path),
        ),
    ]
