# Generated by Django 5.2.17 on 2026-09-09 16:56

import django.db.models.deletion
import fleet.models
import uuid
from django.db import migrations, models


def copy_photo_to_gallery(apps, schema_editor):
    """Move each vehicle's single `photo` into the new gallery as its first
    image. Only the DB pointer moves — the file itself stays where it is in
    the bucket, so nothing is re-uploaded and nothing is deleted.
    """
    Vehicle = apps.get_model("fleet", "Vehicle")
    VehiclePhoto = apps.get_model("fleet", "VehiclePhoto")
    VehiclePhoto.objects.bulk_create(
        [
            VehiclePhoto(vehicle_id=vehicle.id, image=vehicle.photo.name, position=0)
            for vehicle in Vehicle.objects.exclude(photo="").exclude(photo__isnull=True)
        ]
    )


def restore_photo_from_gallery(apps, schema_editor):
    """Reverse: put the first gallery image back on the vehicle."""
    Vehicle = apps.get_model("fleet", "Vehicle")
    VehiclePhoto = apps.get_model("fleet", "VehiclePhoto")
    for photo in VehiclePhoto.objects.order_by("vehicle_id", "position", "created_at"):
        # Only the first photo per vehicle survives — the column holds one.
        Vehicle.objects.filter(id=photo.vehicle_id, photo="").update(photo=photo.image.name)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_driver_photo_alter_guard_photo'),
    ]

    # Order matters: the gallery table has to exist and be populated from
    # `Vehicle.photo` before that column is dropped, or the photos are lost.
    operations = [
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=fleet.models.vehicle_photo_path)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.RunPython(copy_photo_to_gallery, restore_photo_from_gallery),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo',
        ),
    ]
