# Generated by Django 5.2.17 on 2026-09-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_odometer_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelentry',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
