# Generated by Django 5.2.17 on 2026-09-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kiosk_device_binding'),
        ('fleet', '0007_fuel_odometer_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelentry',
            name='kiosk_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='accounts.kioskdevice'),
        ),
        migrations.AddField(
            model_name='trip',
            name='kiosk_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='accounts.kioskdevice'),
        ),
    ]
