# Generated by Django 5.2.17 on 2026-09-01 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_remove_guard_assigned_gate_id_guard_assigned_gate_and_more'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(blank=True, default='', max_length=60)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='masterdata.documenttypemaster')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['expiry_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('driver__isnull', True), ('vehicle__isnull', False)), models.Q(('driver__isnull', False), ('vehicle__isnull', True)), _connector='OR'), name='document_has_exactly_one_owner')],
            },
        ),
    ]
