# Generated by Django 5.2.17 on 2026-08-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('year', models.PositiveIntegerField()),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'year'), name='unique_sequence_scope_year')],
            },
        ),
    ]
