# Generated by Django 5.2.17 on 2026-09-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_soon_km', models.PositiveIntegerField(default=1000)),
                ('urgent_km', models.PositiveIntegerField(default=500)),
            ],
        ),
    ]
