# Generated by Django 5.2.17 on 2026-10-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_fleetsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetsettings',
            name='kiosk_release_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
